More and better package manager aliases

diff --git a/core/.config/aliases/suse b/core/.config/aliases/suse
--- a/core/.config/aliases/suse
+++ b/core/.config/aliases/suse
@@ -2,29 +2,39 @@
 
 check_suse() {
     if [ -f /etc/os-release ]; then
-        name="$(cat /etc/os-release | grep '^NAME' | cut -d '=' -f 2 | tr -d '"')"
-
-        if echo $name | grep -qi "suse" ; then
-            return 0
-        fi
+        echo "$(cat /etc/os-release | grep '^NAME' | cut -d '=' -f 2 | tr -d '"')" | grep -qi "suse" && return 0
     fi
 
     return 1
 }
 
-if ! check_suse; then
-    return
-fi
+check_suse || return
 
+# p: install
 p() {
-    local ZYPP_PCK_PRELOAD=1
+    # Enable parallel downloads and use modern media backend
+    local ZYPP_PCK_PRELOAD=1 ZYPP_CURL2=1
     sudo zypper update --no-confirm
     [ $# -ne 0 ] && sudo zypper install "$@"
 }
 
+# prm: remove
 alias prm='sudo zypper remove'
-alias pq='sudo zypper search --installed-only | grep -v i+'
-alias pqs='sudo zypper search --installed-only'
-alias pss='sudo zypper search'
-#alias pcl
-#alias pcc
+
+# pq: query all explicitly installed local packages
+alias pq='zypper search --installed-only | grep -v i+'
+
+# pqi: query info about a package
+alias pqi='zypper info'
+
+# pqs: query installed package by name
+alias pqs='zypper search --installed-only'
+
+# pss: search in repositories by name
+alias pss='zypper search'
+
+# pcl: clean up non required packages
+alias pcl='echo "Zypper does not have an easy way to do this, :("'
+
+# pcc: clean up cache
+alias pcc='sudo zypper clean --all'
